

employee_names = ["Abdelshakour,Ashraf Abdelraouf Fathy",
"Abou-Melhem,Wassim",
"Adusumilli,Ramesh",
"Aernoudts,Peter Joseph",
"Al-Salem Saqer,Lana",
"Aourpally,Vasudeva Rao",
"Asano,Andre Jorge",
"Balazuc,Denis",
"Balderas,Cristhian",
"Baldo,Eliseu Folego",
"Baldwin,Amanda",
"Bartish,Arran Gregory",
"Baston,Ariella",
"Belala,Yacine",
"Bogatchkina,Tatiana",
"Boissonneault,Sebastien",
"Burdujoc,Ioana Nora",
"Bussiere,Richard",
"Caligiuri,Antonio Francesco",
"Calinoiu,Nicole Gina",
"Cardenas-Medina,Juan Enrique",
"Caron,Cedric",
"Caya,David",
"Chikh-ibrahim,Eyad",
"Chugh,Manish",
"Comtois,Richard",
"Costa,Flavius",
"Coull,Sean",
"Demeule,Valerie",
"Desjardins,Gabriel",
"Dipaolo,Angelo",
"Do,Dang Khoa",
"Dupont,Karine",
"Estefan Elola,Luis Alberto",
"Erkal,Serra",
"Fadous,Georges",
"Fernandez,Laurent",
"Firdjanova,Diana",
"Fornari,Samantha",
"Gammon,John",
"Garbev,Assen",
"Godin,Martin",
"Gollapudi,Kasivisweswara Sharma",
"Gombert,Florian",
"Gong,Ke",
"Hanna,Atheer",
"Harder,Maddison",
"Hernandez,Gabriel",
"Hollen,Erin",
"Hussain,Tenveer",
"Jean,Raynold JR",
"Johnson,David W",
"Joly,Benoit",
"Joubin, Thomas",
"Karimi,Behnam",
"Kearney,Bruce M",
"Mohamed Kleit",
"Kostin,Vyacheslav",
"Kovalenko,Sergey",
"Kulovics,Stephanie",
"Kumar,Arvind",
"Langlais, Eric",
"LeBlanc,Jean-Philippe",
"Li Loong,Lindy",
"Lichocki, Julie Anne",
"Liu,Quan",
"Lizotte,Anne",
"Lubana,Amarbir Singh",
"Mansoura Liamani,Cherifa",
"Moore, Paul Anthony",
"Mornet,Olivier",
"Oliveira,Deyvisson",
"Pant,Erwin",
"Paruchuri,Jaswanth",
"Perreault,Liza",
"Poliarush,Oksana ",
"Postacchini,Leonardo",
"Potluri,Aneesh",
"Quintana,Maria-Luisa",
"Ramdani,Seddik",
"Ammar, Muhammad",
"Ribeiro,Bruno Luiz S",
"Richard,Nicolas",
"Romero Del Bosque,Sergio",
"Rybakov,Sergei",
"Sathi,Venkata R",
"Schneider,Ralf",
"Sellathurai,Sasitharan",
"Sellathurai,Vithiyatharan",
"Shamne,Yury",
"Sharma,Abhishek",
"Sharma,Nidhi",
"Siatetska,Dzvenyslava",
"Sirois,Roxanne",
"Tardif,Daniel",
"Tortajada,Vincent-Julien",
"Trepanier,Erik",
"Urban,Pawel Adam",
"Ven,Vannadine",
"Volynets,Artem",
"Vyas,Chirag",
"Vyas,Vaishalibahen",
"Wang,Ruo Nong",
"Xi,Zhihua",
"Xu,Jie",
"Belanger,Larry",
"Callender,Ron Andrew",
"Cerro,Leah",
"Cote,Jason",
"Dentry,Beverly Darlene",
"Fei,Feigang",
"Guindon-Slater,Patrick",
"Hatajlo,Maria Eleftheria",
"Lemire,Jean-Francois",
"McGurn,Steven",
"Riel,Jeannie",
"Thomas, Jean Nicholas",
"Volkovich,Oleg"]